part of 'go_screen.dart';

LatLngBounds _latLngBoundsFromCoordinatesEntities(
  Iterable<CoordinatesEntity> list,
) {
  final latitudes = list.map((e) => e.latitude);
  final northest = latitudes.calculateMax();
  final southest = latitudes.calculateMin();
  final longitudes = list.map((e) => e.longitude);
  final eastest = longitudes.calculateMax();
  final westest = longitudes.calculateMin();
  final northeast = LatLng(northest, eastest);
  final southwest = LatLng(southest, westest);
  final latLngBounds = LatLngBounds(
    northeast: northeast,
    southwest: southwest,
  );
  return latLngBounds;
}

class _GoViewModel extends ViewModel<GoScreen> {
  final Completer<GoogleMapController> gmapCtlCompleter;

  const _GoViewModel(
    super.context,
    super.ref, {
    required this.gmapCtlCompleter,
  });

  VoidCallback? useEffectHook() {
    final flagRepo = getIt.call<IInitialDisclaimersShownRepo>();
    flagRepo.fetchDidShowNotResponsibleForRouteAccuracyDialog().then(
      (didShow) {
        if (didShow) return;
        WidgetsBinding.instance.addPostFrameCallback((_) {
          if (!context.mounted) return;
          context.simpleDialog(
            title: 'Disclaimer',
            content:
                'pointr is not affiliated with People\'s Bus Service, the Government of Sindh or other relevant agencies.\n\nGiven routes may be subject to change and inaccuracy. Please confirm from other sources before planning your route.\n\nPlease download the official People\'s Bus Service App for official information and for using the digital ticketing system.',
          );
          flagRepo.setNotResponsibleForRouteAccuracyDialogShown();
        });
      },
    );
    return null;
  }

  bool get areBothStopsSet => ref.watch(
        bothStopsProvider.select(
          (e) => e.hasFrom & e.hasTo,
        ),
      );

  void onBackBtnPressed() {
    final searchFocusNode = LocSearchBarWithOverlay.searchFocusNode;
    if (searchFocusNode.hasFocus) return searchFocusNode.unfocus();
    if (ref.watch(toStopProvider) != null) {
      return ref.read(toStopProvider.notifier).state = null;
    }
    if (ref.watch(fromStopProvider) != null) {
      return ref.read(fromStopProvider.notifier).state = null;
    }
    return context.pop();
  }

  Future<void> onSuggestionSelected(AddressEntity place) async {
    final mapCtl = await gmapCtlCompleter.future;
    mapCtl.animateCamera(
      CameraUpdate.newLatLngZoom(
        LatLng(
          place.coordinates.latitude,
          place.coordinates.longitude,
        ),
        15,
      ),
    );
  }

  /// only animates if both stops are set
  Future<void> _animateCameraToBoundsOfStops() async {
    final from = ref.read(fromStopProvider)?.coordinates;
    if (from == null) return;
    final to = ref.read(toStopProvider)?.coordinates;
    if (to == null) return;
    final newBounds = _latLngBoundsFromCoordinatesEntities([from, to]);
    final mapCtl = await gmapCtlCompleter.future;
    mapCtl.animateCamera(
      CameraUpdate.newLatLngBounds(newBounds, 36),
    );
  }

  Future<void> _showImperfectAlgorithmDialog() async {
    final flagRepo = getIt.call<IInitialDisclaimersShownRepo>();
    flagRepo.fetchDidShowAlgorithmImperfectDialog().then(
      (didShow) {
        if (didShow) return;
        WidgetsBinding.instance.addPostFrameCallback((_) {
          if (!context.mounted) return;
          context.simpleDialog(
            title: 'Disclaimer',
            content:
                'The route suggestions provided by this app are generated by an algorithm that is still being refined. Please note that the algorithm does not yet support split-route journeys (e.g., taking multiple buses for the optimal route), and the recommendations may have room for improvement',
          );
          flagRepo.setAlgorithmImperfectDialogShown();
        });
      },
    );
  }

  Future<void> onStopSet() async {
    final mapCtl = await gmapCtlCompleter.future;
    final mapLatLng = await mapCtl.centerLatLng;
    await context.loaderWithErrorDialog(
      () => updateStopProvider(ref, mapLatLng),
    );
    _animateCameraToBoundsOfStops();
    if (areBothStopsSet) _showImperfectAlgorithmDialog();
  }

  String get selectLocBtnLabel {
    final currentlyPickingStop = ref
            .watch(
              currentlyPickingDirectionTypeProvider,
            )
            ?.name
            .toUpperCase() ??
        "";
    return "Set $currentlyPickingStop location";
  }
}
